# Generated by Django 5.2 on 2025-04-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignmanager',
            field=models.TextField(blank=True, null=True),
        ),
    ]
