# Generated by Django 5.2 on 2025-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_assignmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignmanager',
            field=models.TextField(blank=True, null=True),
        ),
    ]
